sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run --rm web composer install -o -n
    - docker-compose run --rm php bin/console cache:clear
    - docker-compose run --rm web bin/console security:check
