sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run --rm web composer install -o -n
    - docker-compose run --rm web php bin/console security:check
    - docker-compose run --rm web vendor/bin/behat ./features/
