api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional


app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

app_controller:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api_login_check:
    path: /api/login_check

test_tree:
    path: '/api/tests/{id}/tree'
    methods:  ['GET']
    defaults:
        _controller: 'AppBundle:Test:tree'
        _api_resource_class: 'AppBundle\Entity\Test'
        _api_item_operation_name: 'tree'