# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    listener.mcq_answer:
        class: AppBundle\EventSubscriber\McqAnswerSubscriber
        arguments: ['@app.redis.client']


    listener.alert:
        class: AppBundle\EventSubscriber\AlertSubscriber
        arguments: ['@app.redis.client']

    listener.feedback:
        class: AppBundle\EventSubscriber\FeedbackSubscriber
        arguments: ['@app.redis.client']

    listener.discipline:
        class: AppBundle\EventSubscriber\DisciplineSubscriber
        arguments: ['@service_container']
