services:
    question.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { test: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'question.search' } ]

