# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
imports:
    - { resource: 'services_admin.yml' }
    - { resource: 'services_event_listener.yml' }
    - { resource: 'services_voter.yml' }
    - { resource: 'services_filter.yml' }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    security.authentication.provider.sso:
        class: BeSimple\SsoAuthBundle\Security\Core\Authentication\Provider\SsoAuthenticationOverrideProvider
        abstract: true
        public: false
        arguments: [~, "@security.user_checker", ~, ~, "%security.authentication.hide_user_not_found%","@fos_user.user_manager"]

    listener.voter:
        class: AppBundle\EventSubscriber\AccessListener
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 3}

    app.redis.client:
        class: Predis\Client
        arguments: ['tcp://redis:6379']

    app.git.client:
        class: AppBundle\Service\Git

    app.importer.yaml:
        class: AppBundle\Service\YamlImporter
        arguments: ["@doctrine.orm.entity_manager"]

    app.mcq_answer_validator:
        class: AppBundle\Service\McqAnswerValidator
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: validator.constraint_validator }

    app.text_answer_validator:
        class: AppBundle\Service\TextAnswerValidator
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: validator.constraint_validator }

