services:
    question.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { test: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'question.search' } ]

    discipline.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { part: 'exact'} ]
        tags:      [ { name: 'api_platform.filter', id: 'discipline.search' } ]

    session.search_filter:
            parent:    'api_platform.doctrine.orm.search_filter'
            arguments: [ { discipline: 'exact'} ]
            tags:      [ { name: 'api_platform.filter', id: 'session.search' } ]