# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.discipline:
        class: AppBundle\Admin\DisciplineAdmin
        arguments: [~, AppBundle\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Discipline }

    admin.commentary:
        class: AppBundle\Admin\CommentaryAdmin
        arguments: [~, AppBundle\Entity\Commentary, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentary }

    admin.mcq_answer:
        class: AppBundle\Admin\McqAnswerAdmin
        arguments: [~, AppBundle\Entity\McqAnswer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: MCQ Answer }

    admin.mcq_choice:
        class: AppBundle\Admin\McqChoiceAdmin
        arguments: [~, AppBundle\Entity\McqChoice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: MCQ Choice }

    admin.question:
        class: AppBundle\Admin\QuestionAdmin
        arguments: [~, AppBundle\Entity\Question, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Question }

    admin.session:
        class: AppBundle\Admin\SessionAdmin
        arguments: [~, AppBundle\Entity\Session, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Session }

    admin.subject:
        class: AppBundle\Admin\SubjectAdmin
        arguments: [~, AppBundle\Entity\Subject, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subject }
