# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.discipline:
        class: AppBundle\Admin\DisciplineAdmin
        arguments: [~, AppBundle\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Discipline }

    admin.commentary:
        class: AppBundle\Admin\CommentaryAdmin
        arguments: [~, AppBundle\Entity\Commentary, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commentary }

    admin.mcq_answer:
        class: AppBundle\Admin\McqAnswerAdmin
        arguments: [~, AppBundle\Entity\McqAnswer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: MCQ Answer }

    admin.mcq_choice:
        class: AppBundle\Admin\McqChoiceAdmin
        arguments: [~, AppBundle\Entity\McqChoice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: MCQ Choice }

    admin.question:
        class: AppBundle\Admin\QuestionAdmin
        arguments: [~, AppBundle\Entity\Question, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Question }

    admin.session:
        class: AppBundle\Admin\SessionAdmin
        arguments: [~, AppBundle\Entity\Session, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Session }

    admin.subject:
        class: AppBundle\Admin\SubjectAdmin
        arguments: [~, AppBundle\Entity\Subject, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Subject }

    admin.test:
        class: AppBundle\Admin\TestAdmin
        arguments: [~, AppBundle\Entity\Test, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Test }

    admin.text_answer:
        class: AppBundle\Admin\TextAnswerAdmin
        arguments: [~, AppBundle\Entity\TextAnswer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Text Answer }

    admin.thread:
        class: AppBundle\Admin\ThreadAdmin
        arguments: [~, AppBundle\Entity\Thread, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Thread }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }


    security.authentication.provider.sso:
        class: BeSimple\SsoAuthBundle\Security\Core\Authentication\Provider\SsoAuthenticationOverrideProvider
        abstract: true
        public: false
        arguments: [~, "@security.user_checker", ~, ~, "%security.authentication.hide_user_not_found%"]

    voter.dicipline:
        class: AppBundle\Security\DisciplineVoter
        tags:
            - { name: security.voter }

    voter.mcq_answer:
        class: AppBundle\Security\McqAnswerVoter
        tags:
            - { name: security.voter }

    voter.mcq_choice:
        class: AppBundle\Security\McqChoiceVoter
        tags:
            - { name: security.voter}

    voter.question:
        class: AppBundle\Security\QuestionVoter
        tags:
            - { name: security.voter}

    voter.session:
        class: AppBundle\Security\SessionVoter
        tags:
            - { name: security.voter}

    voter.subject:
        class: AppBundle\Security\SubjectVoter
        tags:
            - { name: security.voter}

    voter.test:
        class: AppBundle\Security\TestVoter
        tags:
            - { name: security.voter}

    voter.text_answer:
        class: AppBundle\Security\TextAnswerVoter
        tags:
            - { name: security.voter}

    voter.thread_message:
        class: AppBundle\Security\ThreadMessageVoter
        tags:
            - { name: security.voter}

    voter.thread:
        class: AppBundle\Security\ThreadVoter
        tags:
            - { name: security.voter}

    voter.user:
        class: AppBundle\Security\UserVoter
        tags:
            - { name: security.voter}